### ISSUE TITLE
NextToken corrupted

### ISSUE THREAD

**Issue by CoMartel** [jameshiew/python-amazon-mws#32]
Hi,

First, thanks a lot for your work! It made it really easy to communicate with MWS.

I'm trying to retrieve all orders since a long time ago, and I have to go through a lot of pages, using "orders_api.list_order_items_by_next_token()"

My issue is that MWS is returning an error : 

`MWSError: <?xml version="1.0"?>                                                                                                                              <ErrorResponse xmlns="https://mws.amazonservices.com/Orders/2013-09-01">                                                                                       <Error>                                                                                                                                                        <Type>Sender</Type>                                                                                                                                          <Code>NextTokenCorrupted</Code>                                                                                                                              <Message>We could not decode your NextToken.</Message>                                                                                                     </Error>                                                                                                                                                     <RequestId>66a476d9-5e39-4749-9d24-0f0eb144c2de</RequestId>                                                                                                </ErrorResponse> `

My Token : `'94HPGhjwKyV/YYuZQbKv1QafEPREmauvizt1MIhPYZZbsgeHy/DuWGI4ng+mAxhBnCRKY29ynn3NeGyEmOrLe7q8xqAchQNKtU38YwqRuVIwqcbUqh/LhCJ0wMvlylZkE3RvwDUQBA2PLkbo+RzWuc0I2oB+AODGnOuH9R+FS+UrZQy/V771Wx35jNz11rwFrh4UqkkfQWA2QiSqpH/3gzvpWxLDu6V0kSSzHy0mGpCfpVJGS+vu5pFHMXy6XL5l/6rjAfCll94wI2FDUn7uCTzBkCWg0Z/wsJdJobvDtjaUELdOx1y44x2EM4mxRhI1BfS02qhrrgmld87/uwC4WaomF+AypslNStz4vwzMbNU93cf9JM/dXCDd8WY6S5qIC7lkadWl+YjiGdvkjrjldO07RNBq9UDfR2MsVNGnbkXLc/qP8a7QJ8Een7QBpmb/G8zE6YuflsyoTzmSGfWp2PyAULdxUEMyTzGCBmL1RoSabG1W2DI/elTKWZCcypVTY6OSkm5sDP9ZJvmuQ0mk4Epd8Re7bpJfPMG4jNqghnlDZBmR6xJsEr5KRLN5wRPF1YGxuBKk5+eybflF5uWu/iHPH7EsHndai5Q+A8Zi3sU='`

What could be the issue? Any tips on how to fix this ?

**Comment by CoMartel** [comment]
Sure : 
```
marketplaceids = [
    "A1PA6795UKMFR9",
    "A1RKKUPIHCS9HS",
    "A13V1IB3VIYZZH",
    "APJ6JRA9NG5V4",
    "A1F83G8C2ARO7P"
]

date_from = datetime.datetime(2015, 11, 26, 14, 51, 49, tzinfo=<UTC>)

ret = orders_api.list_orders(lastupdatedafter = date_from, marketplaceids = marketplaceids, orderstatus = ["Shipped"])
json = ret.parsed

```
So up until now, everything works fine. Then I try to go to the next page : 

`ret = orders_api.list_order_items_by_next_token( token = json['NextToken']['value'])`

And I get this error, with the traceback  : 

```
---------------------------------------------------------------------------                                                                                  MWSError                                  Traceback (most recent call last)
<ipython-input-43-85ddb75d5434> in <module>() 
----> 1 ret2 = orders_api.list_order_items_by_next_token( token = (json['NextToken']['value']).encode('ISO-8859-1'))

C:\ProgramData\Anaconda2\lib\site-packages\mws\mws.pyc in list_order_items_by_next_token(self, token) 
460     def list_order_items_by_next_token(self, token):
461         data = dict(Action='ListOrderItemsByNextToken', NextToken=token)
--> 462         return self.make_request(data)
463
464

C:\ProgramData\Anaconda2\lib\site-packages\mws\mws.pyc in make_request(self, extra_data, method, **kwargs)
224             error = MWSError(str(e.response.text))
225             error.response = e.response 
--> 226             raise error
227
228         # Store the response object in the parsed_response for quick access     
```          

                                                                                                                                                                                                                        

> `MWSError: <?xml version="1.0"?>                                                                                                                              <ErrorResponse xmlns="https://mws.amazonservices.com/Orders/2013-09-01">                                                                                       <Error>                                                                                                                                                        <Type>Sender</Type>                                                                                                                                          <Code>NextTokenCorrupted</Code>                                                                                                                              <Message>We could not decode your NextToken.</Message>                                                                                                     </Error>                                                                                                                                                     <RequestId>44663e39-e2de-496b-8a2f-c881e261e485</RequestId>                                                                                                </ErrorResponse>`

**Comment by GriceTurrble** [comment]
I see the issue. You are calling `list_orders` at first, which gives you a next_token for that operation. The following call should be `list_orders_by_next_token`.

Whereas, `list_order_items` and `list_order_items_by_next_token` is a different set of operations for MWS. They would expect a next_token specific to that operation: when they don't recognize it as coming from that operation, they will throw an error.

Try the `list_orders_by_next_token` call, instead, please.

**Comment by CoMartel** [comment]
hum...
How dumb can I be ? ^^
Well, thank you very much for you help and reactivity. Keep up with this good work !
